package kanga;
/* Generated By:JavaCC: Do not edit this line. KangaParserConstants.java */
public interface KangaParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int LPAREN = 9;
  int RPAREN = 10;
  int LBRACE = 11;
  int RBRACE = 12;
  int LSQPAREN = 13;
  int RSQPAREN = 14;
  int DOT = 15;
  int LT = 16;
  int LE = 17;
  int GT = 18;
  int GE = 19;
  int NE = 20;
  int EQ = 21;
  int PLUS = 22;
  int MINUS = 23;
  int AND = 24;
  int OR = 25;
  int NOT = 26;
  int TIMES = 27;
  int MAIN = 28;
  int CODE = 29;
  int HALLOCATE = 30;
  int SPILLEDARG = 31;
  int END = 32;
  int NOOP = 33;
  int MOVE = 34;
  int CALL = 35;
  int ERROR = 36;
  int PRINT = 37;
  int BEGIN = 38;
  int RETURN = 39;
  int JUMP = 40;
  int CJUMP = 41;
  int HSTORE = 42;
  int HLOAD = 43;
  int ALOAD = 44;
  int ASTORE = 45;
  int PASSARG = 46;
  int MEM = 47;
  int TEMP = 48;
  int ARG = 49;
  int ZERO = 50;
  int at = 51;
  int v0 = 52;
  int v1 = 53;
  int a0 = 54;
  int a1 = 55;
  int a2 = 56;
  int a3 = 57;
  int t0 = 58;
  int t1 = 59;
  int t2 = 60;
  int t3 = 61;
  int t4 = 62;
  int t5 = 63;
  int t6 = 64;
  int t7 = 65;
  int s0 = 66;
  int s1 = 67;
  int s2 = 68;
  int s3 = 69;
  int s4 = 70;
  int s5 = 71;
  int s6 = 72;
  int s7 = 73;
  int t8 = 74;
  int t9 = 75;
  int k0 = 76;
  int k1 = 77;
  int gp = 78;
  int sp = 79;
  int fp = 80;
  int ra = 81;
  int INTEGER_LITERAL = 82;
  int IDENTIFIER = 83;
  int LETTER = 84;
  int DIGIT = 85;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"LT\"",
    "\"LE\"",
    "\"GT\"",
    "\"GE\"",
    "\"NE\"",
    "\"EQ\"",
    "\"PLUS\"",
    "\"MINUS\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"TIMES\"",
    "\"MAIN\"",
    "\"CODE\"",
    "\"HALLOCATE\"",
    "\"SPILLEDARG\"",
    "\"END\"",
    "\"NOOP\"",
    "\"MOVE\"",
    "\"CALL\"",
    "\"ERROR\"",
    "\"PRINT\"",
    "\"BEGIN\"",
    "\"RETURN\"",
    "\"JUMP\"",
    "\"CJUMP\"",
    "\"HSTORE\"",
    "\"HLOAD\"",
    "\"ALOAD\"",
    "\"ASTORE\"",
    "\"PASSARG\"",
    "\"MEM\"",
    "\"TEMP\"",
    "\"ARG\"",
    "\"zero\"",
    "\"at\"",
    "\"v0\"",
    "\"v1\"",
    "\"a0\"",
    "\"a1\"",
    "\"a2\"",
    "\"a3\"",
    "\"t0\"",
    "\"t1\"",
    "\"t2\"",
    "\"t3\"",
    "\"t4\"",
    "\"t5\"",
    "\"t6\"",
    "\"t7\"",
    "\"s0\"",
    "\"s1\"",
    "\"s2\"",
    "\"s3\"",
    "\"s4\"",
    "\"s5\"",
    "\"s6\"",
    "\"s7\"",
    "\"t8\"",
    "\"t9\"",
    "\"k0\"",
    "\"k1\"",
    "\"gp\"",
    "\"sp\"",
    "\"fp\"",
    "\"ra\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
