//
// Generated by JTB 1.3.2
//

package piglet.syntaxtree;

/**
 * Grammar production:
 * f0 -> Operator()
 * f1 -> Exp()
 * f2 -> Exp()
 */
public class BinOp implements Node {
   public Operator f0;
   public Exp f1;
   public Exp f2;

   public BinOp(Operator n0, Exp n1, Exp n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public void accept(piglet.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(piglet.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(piglet.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(piglet.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

