package piglet;
/* Generated By:JavaCC: Do not edit this line. PigletParserConstants.java */
public interface PigletParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int LPAREN = 9;
  int RPAREN = 10;
  int LBRACE = 11;
  int RBRACE = 12;
  int LSQPAREN = 13;
  int RSQPAREN = 14;
  int DOT = 15;
  int LT = 16;
  int LE = 17;
  int GT = 18;
  int GE = 19;
  int NE = 20;
  int EQ = 21;
  int PLUS = 22;
  int MINUS = 23;
  int AND = 24;
  int OR = 25;
  int NOT = 26;
  int TIMES = 27;
  int MAIN = 28;
  int CODE = 29;
  int HALLOCATE = 30;
  int END = 31;
  int NOOP = 32;
  int MOVE = 33;
  int CALL = 34;
  int ERROR = 35;
  int PRINT = 36;
  int BEGIN = 37;
  int RETURN = 38;
  int JUMP = 39;
  int CJUMP = 40;
  int HSTORE = 41;
  int HLOAD = 42;
  int MEM = 43;
  int TEMP = 44;
  int ARG = 45;
  int INTEGER_LITERAL = 46;
  int IDENTIFIER = 47;
  int LETTER = 48;
  int DIGIT = 49;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"LT\"",
    "\"LE\"",
    "\"GT\"",
    "\"GE\"",
    "\"NE\"",
    "\"EQ\"",
    "\"PLUS\"",
    "\"MINUS\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"TIMES\"",
    "\"MAIN\"",
    "\"CODE\"",
    "\"HALLOCATE\"",
    "\"END\"",
    "\"NOOP\"",
    "\"MOVE\"",
    "\"CALL\"",
    "\"ERROR\"",
    "\"PRINT\"",
    "\"BEGIN\"",
    "\"RETURN\"",
    "\"JUMP\"",
    "\"CJUMP\"",
    "\"HSTORE\"",
    "\"HLOAD\"",
    "\"MEM\"",
    "\"TEMP\"",
    "\"ARG\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
